from customtkinter import *
from customtkinter import CTkImage
from tkinter import *
from tkinter import ttk
import csv
from pathlib import Path
from MAIN_WINDOW_CONSTANTS import PICTURE_PREVIEW_HEIGHT, PICTURE_PREVIEW_WIDTH

# DATA_DIR = Path("data")
# POSTS_FILE = DATA_DIR / "petitions.csv"
# REACTIONS_FILE = DATA_DIR / "reactions.csv"
# COMMENTS_FILE = DATA_DIR / "comments.csv"
# ALL_COMMENTS_FILE = DATA_DIR / "all_comments.csv"

# # Global variables initialization
# comment_reactions = {}  
# notifications = []
# current_petition_index = 0  # Add this if not already defined

# # Data initialization with error handling
# DATA_DIR.mkdir(exist_ok=True)

WINDOW = ''
WINDOW_HEIGHT = 600   
WINDOW_WIDTH = 920 #820 increased from 820 to accomodate the description textbox
WINDOW_TITLE = 'Here'     
WINDOW_ICONBITMAP = 'HERE_WINDOW_ICON.ico'


TAB_HEIGHT = 500
TAB_WIDTH = 400
GRID_COLUMNCONFIGURE = 1
GRID_ROWCONFIGURE = 1
ALL = 'All Petitions'
PENDING = "Pending Petitions"
APPROVED = 'Approved Petitions'
SUSPENDED = "Suspended"
SETTINGS = "Settings"

'''changed the TAB_TEXT referencing style to using the proper name for each, for easier and clearer referencing'''

FRAME_WIDTH = 640
FRAME_HEIGHT = 600
FRAME_BACKGROUND = '#0F0F0F'

HOME_IMAGE_LABEL = NONE
HOME_IMAGE_LABEL_WIDTH = FRAME_WIDTH +15
HOME_IMAGE_LABEL_HEIGHT = FRAME_HEIGHT - 200
HOME_IMAGE_LABEL_BACKGROUND = '#123456' # CHANGED IT FROM '#EE0000' AS THAT WAS TOO BRIGHT, WASN'T MATCHING BACKGROUND HURT
HOME_IMAGE_LABEL_ROW = 0
HOME_IMAGE_LABEL_COLUMN = 0
HOME_IMAGE_LABEL_ROWSPAN = 5
HOME_IMAGE_LABEL_COLUMNSPAN = 1
HOME_IMAGE_LABEL_STICKY = NSEW

DEFAULT_IMAGE =   r"MAIN_WINDOW_ICON.jpg"
RESIZED_IMAGE_TUPLE = (500,500)


# Image Info Label Constants
IMAGE_INFO_LABEL_TEXT = "Image Info"
IMAGE_INFO_LABEL_BACKGROUND = "white"
IMAGE_INFO_LABEL_HEIGHT = 6
IMAGE_INFO_LABEL_WIDTH = 35
IMAGE_INFO_LABEL_ROW = 0
IMAGE_INFO_LABEL_COLUMN = 1
IMAGE_INFO_LABEL_STICKY = "nsew"
IMAGE_INFO_LABEL_PADX = 1
IMAGE_INFO_LABEL_PADY = 1

# # Example of adding comments (you can dynamically add comments in a loop)
# def load_comments(petition_id, comments_file='comments.csv', all_comments_file='all_comments.csv'):
#     comments_dict = {}
    
#     # Load comments.csv to get comment IDs for the given petition_id
#     with open(comments_file, mode='r', newline='') as file:
#         reader = csv.DictReader(file)
#         comment_ids = [row['comment_id'] for row in reader if row['petition_id'] == str(petition_id)]
    
#     # Load all_comments.csv to get the actual comments using the comment IDs
#     with open(all_comments_file, mode='r', newline='') as file:
#         reader = csv.DictReader(file)
#         for row in reader:
#             if row['comment_id'] in comment_ids:
#                 comments_dict[row['comment_id']] = {
#                     "user": row['user'],
#                     "comment": row['comment']
#                 }
    
#     return comments_dict

# # Example usage
# petition_id = 1  # Replace with the actual petition ID
# example_comments = load_comments(petition_id)


# Comments Section Frame Constants
COMMENTS_SECTION_FRAME_WIDTH = IMAGE_INFO_LABEL_WIDTH
COMMENTS_SECTION_FRAME_HEIGHT = 200
COMMENTS_SECTION_FRAME_BACKGROUND = "#FFFFFF"
COMMENTS_SECTION_FRAME_ROW = 1  # Adjusted to match IMAGE_INFO_LABEL_ROW + 1
COMMENTS_SECTION_FRAME_COLUMN = 1  # Same as IMAGE_INFO_LABEL_COLUMN
COMMENTS_SECTION_FRAME_STICKY = "nsew"
COMMENTS_SECTION_FRAME_PADX = 2
COMMENTS_SECTION_FRAME_PADY = 2
COMMENTS_SECTION_SCROLLBAR_COLOR = "#CCCCCC"
COMMENTS_SECTION_SCROLLBAR_HOVER_COLOR = "#999999"

# Comment Frame Constants
COMMENT_FRAME_BACKGROUND = "#F0F0F0"
COMMENT_FRAME_CORNER_RADIUS = 5
COMMENT_FRAME_PADY = 5

# Comment Text Constants
COMMENT_USER_FONT = ("Arial", 12, "bold")
COMMENT_USER_TEXT_COLOR = "#333333"
COMMENT_TEXT_FONT = ("Arial", 11)
COMMENT_TEXT_COLOR = "#555555"
COMMENT_PADX = 5


# Reaction button constants
COMMENT_REACTION_BUTTON_WIDTH = 1
COMMENT_REACTION_BUTTON_HEIGHT = 1
COMMENT_REACTION_BUTTON_FONT = ("Arial", 12)
COMMENT_REACTION_BUTTON_BG = "#123456"
COMMENT_REACTION_BUTTON_HOVER_COLOR = "#C0C0C0"
COMMENT_REACTION_BUTTON_SPACING = 5

REACTIONS_FRAME_HEIGHT = 100
REACTIONS_FRAME_WIDTH = 8 
REACTION_FRAME_RELX = 0 #0.9
REACTION_FRAME_RELY = 0.5 #Changed from 0.65 to 0.58 to fit in agree/disagree stats -AG🟨  #never mind, having 1,1 moved it outside the frame boundaies #0.9 this win become 1, 1, which will always place it at the bottom right corner    
REACTION_FRAME_BACKGROUND = '#0123FF'
NUMBER_OF_BUTTONS = 8 #changed from 5 to 6   
REACTION_BUTTON_WIDTH = REACTIONS_FRAME_WIDTH
REACTION_BUTTON_HEIGHT = REACTIONS_FRAME_HEIGHT*NUMBER_OF_BUTTONS
REACTION_BUTTON_CORNER_RADIUS = 5

AGREE_STAT = NONE
AGREE_STAT_TEXT = 'Agree: '
AGREE_STAT_BG_COLOR = 'GREEN'
AGREE_STAT_FG_COLOR = 'WHITE'
AGREE_STAT_CORNER_RADIUS = 5
AGREE_STAT_ROW = 0
AGREE_STAT_COLUMN = 0
AGREE_STAT_PADX = 0
AGREE_STAT_PADY = 0
AGREE_STAT_STICKY = NSEW

DISAGREE_STAT = NONE
DISAGREE_STAT_TEXT = 'Disagree: '
DISAGREE_STAT_BG_COLOR = 'RED'
DISAGREE_STAT_FG_COLOR = 'WHITE'
DISAGREE_STAT_CORNER_RADIUS = 0
DISAGREE_STAT_ROW = 1
DISAGREE_STAT_COLUMN = 0
DISAGREE_STAT_PADX = 0
DISAGREE_STAT_PADY = 0
DISAGREE_STAT_STICKY = NSEW

ACCEPT_BUTTON_BACKGROUND = 'GREEN'
ACCEPT_BUTTON_TEXT = '✅ Accept'
ACCEPT_BUTTON_ROW = 2
ACCEPT_BUTTON_COLUMN = 0
ACCEPT_BUTTON_PADX = 0
ACCEPT_BUTTON_PADY = 0
ACCEPT_BUTTON_STICKY = NSEW

REJECT_BUTTON_BACKGROUND = 'RED'
REJECT_BUTTON_TEXT = '❌ Reject'
REJECT_BUTTON_ROW = 3
REJECT_BUTTON_COLUMN = 0
REJECT_BUTTON_PADX = 0
REJECT_BUTTON_PADY = 0
REJECT_BUTTON_STICKY = NSEW

INFO_BUTTON_BACKGROUND = 'YELLOW'
INFO_BUTTON_TEXT = 'ℹ️ Description'
INFO_BUTTON_ROW = 4
INFO_BUTTON_COLUMN = 0
INFO_BUTTON_PADX = 0
INFO_BUTTON_PADY = 0
INFO_BUTTON_STICKY = NSEW

QUESTION_BUTTON_BACKGROUND = 'BLUE'
QUESTION_BUTTON_TEXT = '🌐 Google it'
QUESTION_BUTTON_ROW = 5
QUESTION_BUTTON_COLUMN = 0
QUESTION_BUTTON_PADX = 0
QUESTION_BUTTON_PADY = 0
QUESTION_BUTTON_STICKY = NSEW

SHARE_BUTTON_BACKGROUND = 'WHITE'
SHARE_BUTTON_FOREGROUND = 'BLACK'
SHARE_BUTTON_TEXT = '🔗 Share'
SHARE_BUTTON_ROW = 6
SHARE_BUTTON_COLUMN = 0
SHARE_BUTTON_PADX = 0
SHARE_BUTTON_PADY = 0
SHARE_BUTTON_STICKY = NSEW

# To be kept, and potentially added in future versions
# NEXT_PREVIOUS_BUTTON_FRAME = NONE
# NEXT_PREVIOUS_BUTTON_FRAME_ROW = 2
# NEXT_PREVIOUS_BUTTON_FRAME_COLUMN = 0
# NEXT_PREVIOUS_BUTTON_FRAME_STICKY = NSEW
# NEXT_PREVIOUS_BUTTON_FRAME_PADX = 0
# NEXT_PREVIOUS_BUTTON_FRAME_PADY = 0

# next_previous_button_frame = Frame(
#     master= tab_view.tab(ALL),
# )
# next_previous_button_frame.grid(
#     row = NEXT_PREVIOUS_BUTTON_FRAME_ROW,
#     column = NEXT_PREVIOUS_BUTTON_FRAME_COLUMN,
#     sticky = NEXT_PREVIOUS_BUTTON_FRAME_STICKY,
#     padx= NEXT_PREVIOUS_BUTTON_FRAME_PADY,
#     pady= NEXT_PREVIOUS_BUTTON_FRAME_PADY
# )'''

NEXT_PETITION_BUTTON = NONE
NEXT_PETITION_BUTTON_TEXT = 'Next Petition ➡️'
NEXT_PETITION_BUTTON_ROW = 2
NEXT_PETITION_BUTTON_COLUMN = 0
NEXT_PETITION_BUTTON_STICKY = NSEW
NEXT_PETITION_BUTTON_PADX = 10
NEXT_PETITION_BUTTON_PADY = 0

PREVIOUS_PETITION_BUTTON = NONE
PREVIOUS_PETITION_BUTTON_TEXT = 'Previous Petition ⬅️'
PREVIOUS_PETITION_BUTTON_ROW = 3
PREVIOUS_PETITION_BUTTON_COLUMN = 0
PREVIOUS_PETITION_BUTTON_STICKY = NSEW
PREVIOUS_PETITION_BUTTON_PADX = 10
PREVIOUS_PETITION_BUTTON_PADY = 0

'''NEW PETITION TAB CONSTANTS'''

NEW_PETITION_FRAME = NONE # JUST TO MAKE IT EASIER - INSTEAD OF TYPING IT REPEATEDLY, THE VARIABE IS NOW AUTOSUGGESTED
NEW_PETITION_BACKGROUND = '#aaadda'
NEW_PETITION_FRAME_WIDTH = WINDOW_WIDTH
NEW_PETITION_FRAME_HEIGHT = 520
NEW_PETITION_FRAME_RELX = 0.02
NEW_PETITION_FRAME_RELY = 0.04
NEW_PETITION_FRAME_RELWIDTH = 1
NEW_PETITION_FRAME_RELHEIGHT = 1
NEW_PETITION_FRAME_BORDER = 2   
NEW_PETITION_FRAME_CURSOR = 'shuttle'
NEW_PETITION_FRAME_PADX = 10
NEW_PETITION_FRAME_PADY = 5

'''Only the picture preview width and height are needed'''
PICTURE_PREVIEW = NONE
PICTURE_PREVIEW_BACKGROUND = 'HOME_WINDOW_ICON.jpg'
PICTURE_PREVIEW_TEXT = 'Click UPLOAD PICTURE to preview your image ➡️'

PICTURE_PREVIEW_WIDTH = PICTURE_PREVIEW_HEIGHT  #check next line #75 this was also for the frame object  #400 was too big for the label
PICTURE_PREVIEW_HEIGHT = PICTURE_PREVIEW_WIDTH #i finally ended up using 500 for the canvas #25 this was for a frame object #400 was too big for the label
PICTURE_PREVIEW_ROW = 0
PICTURE_PREVIEW_ROWSPAN = 1
PICTURE_PREVIEW_COLUMN = 0
PICTURE_PREVIEW_COLUMNSPAN = 1
PICTURE_PREVIEW_PADX = 10
PICTURE_PREVIEW_PADY = 10
PICTURE_PREVIEW_IMAGE = NONE
PICTURE_PREVIEW_IMAGE_SIZE = [400, 400]