from customtkinter import *
from customtkinter import CTkImage




LOGIN_WINDOW_WIDTH = 720
LOGIN_WINDOW_HEIGHT = 540
LOGIN_WINDOW_TITLE = 'Log In to your Account'
LOGIN_WINDOW_APPEARANCE_MODE = 'dark'
LOGIN_WINDOW_CORNER_RADIUS = 20

LOGIN_WINDOW_FRAME_HEIGHT = 400
LOGIN_WINDOW_FRAME_WIDTH = 600
LOGIN_WINDOW_FRAME_BACKGROUND_COLOR = '#F0F0F0'
LOGIN_WINDOW_FRAME_CORNER_RADIUS = 15
LOGIN_WINDOW_FRAME_BORDER_COLOUR = 'blue'

RESIDENT_ID_LABEL_FONT = ('Arial', 20)
RESIDENT_ID_LABEL_TEXT = 'Resident ID:'
RESIDENT_ID_LABEL_CORNER_RADIUS = 5
RESIDENT_ID_LABEL_HEIGHT = 5
RESIDENT_ID_LABEL_WIDTH = 20
RESIDENT_ID_LABEL_BACKGROUND_COLOR = 'blue'
RESIDENT_ID_LABEL_FOREGROUND_COLOR = 'peachpuff'

RESIDENT_PASSWORD_LABEL_FONT = ('Arial', 20)
RESIDENT_PASSWORD_LABEL_TEXT = 'Password:'
RESIDENT_PASSWORD_LABEL_CORNER_RADIUS = 5
RESIDENT_PASSWORD_LABEL_HEIGHT = 5
RESIDENT_PASSWORD_LABEL_WIDTH = 20
RESIDENT_PASSWORD_LABEL_BACKGROUND_COLOR = 'PURPLE'
RESIDENT_PASSWORD_LABEL_FOREGROUND_COLOR = '#0F0F0F'

RESIDENT_ID_ENTRY_CORNER_RADIUS = 5
RESIDENT_ID_ENTRY_FONT = ('Arial', 20)
RESIDENT_ID_ENTRY_WIDTH = 20
RESIDENT_ID_ENTRY_HEIGHT = 5
RESIDENT_ID_ENTRY_BACKGROUND_COLOR = 'RED'
RESIDENT_ID_ENTRY_FOREGROUND_COLOR = 'CYAN'

LOGIN_BUTTON_TEXT = 'Log In!'
LOGIN_BUTTON_CORNER_RADIUS = 5
LOGIN_BUTTON_FONT = ('Arial', 20)
LOGIN_BUTTON_BG = "YELLOW"
LOGIN_BUTTON_FG = "GREEN"
LOGIN_BUTTON_HOVER = True
# LOGIN_BUTTON_HOVER_FG = 'white'
# LOGIN_BUTTON_HOVER_BG = 'green'