from customtkinter import *
from customtkinter import CTkImage
from tkinter import *
from tkinter import ttk
import csv
from pathlib import Path

# DATA_DIR = Path("data")
# POSTS_FILE = DATA_DIR / "petitions.csv"
# REACTIONS_FILE = DATA_DIR / "reactions.csv"
# COMMENTS_FILE = DATA_DIR / "comments.csv"
# ALL_COMMENTS_FILE = DATA_DIR / "all_comments.csv"

# # Global variables initialization
# comment_reactions = {}  
# notifications = []
# current_petition_index = 0  # Add this if not already defined

# # Data initialization with error handling
# DATA_DIR.mkdir(exist_ok=True)

WINDOW = ''
WINDOW_HEIGHT = 600   
WINDOW_WIDTH = 920 #820 increased from 820 to accomodate the description textbox
WINDOW_TITLE = 'Hear'     
WINDOW_ICONBITMAP = 'MAIN_WINDOW_ICON.ico'


TAB_HEIGHT = 500
TAB_WIDTH = 400
GRID_COLUMNCONFIGURE = 1
GRID_ROWCONFIGURE = 1
TRENDS = 'Trends📈'
NEW = "New✨"
RESPONSES = 'Responses📨'
SOLUTIONS = "Solutions✅"
YOU = "You🙂"

'''changed the TAB_TEXT referencing style to using the proper name for each, for easier and clearer referencing'''

FRAME_WIDTH = 640
FRAME_HEIGHT = 600
FRAME_BACKGROUND = '#0F0F0F'

HOME_IMAGE_LABEL = NONE
HOME_IMAGE_LABEL_WIDTH = FRAME_WIDTH +15
HOME_IMAGE_LABEL_HEIGHT = FRAME_HEIGHT - 200
HOME_IMAGE_LABEL_BACKGROUND = '#123456' # CHANGED IT FROM '#EE0000' AS THAT WAS TOO BRIGHT, WASN'T MATCHING BACKGROUND HURT
HOME_IMAGE_LABEL_ROW = 0
HOME_IMAGE_LABEL_COLUMN = 0
HOME_IMAGE_LABEL_ROWSPAN = 5
HOME_IMAGE_LABEL_COLUMNSPAN = 1
HOME_IMAGE_LABEL_STICKY = NSEW

DEFAULT_IMAGE =   r"MAIN_WINDOW_ICON.jpg"
RESIZED_IMAGE_TUPLE = (500,500)


# Image Info Label Constants
IMAGE_INFO_LABEL_TEXT = "Image Info"
IMAGE_INFO_LABEL_BACKGROUND = "white"
IMAGE_INFO_LABEL_HEIGHT = 6
IMAGE_INFO_LABEL_WIDTH = 35
IMAGE_INFO_LABEL_ROW = 0
IMAGE_INFO_LABEL_COLUMN = 1
IMAGE_INFO_LABEL_STICKY = "nsew"
IMAGE_INFO_LABEL_PADX = 1
IMAGE_INFO_LABEL_PADY = 1

# # Example of adding comments (you can dynamically add comments in a loop)
# def load_comments(petition_id, comments_file='comments.csv', all_comments_file='all_comments.csv'):
#     comments_dict = {}
    
#     # Load comments.csv to get comment IDs for the given petition_id
#     with open(comments_file, mode='r', newline='') as file:
#         reader = csv.DictReader(file)
#         comment_ids = [row['comment_id'] for row in reader if row['petition_id'] == str(petition_id)]
    
#     # Load all_comments.csv to get the actual comments using the comment IDs
#     with open(all_comments_file, mode='r', newline='') as file:
#         reader = csv.DictReader(file)
#         for row in reader:
#             if row['comment_id'] in comment_ids:
#                 comments_dict[row['comment_id']] = {
#                     "user": row['user'],
#                     "comment": row['comment']
#                 }
    
#     return comments_dict

# # Example usage
# petition_id = 1  # Replace with the actual petition ID
# example_comments = load_comments(petition_id)


# Comments Section Frame Constants
COMMENTS_SECTION_FRAME_WIDTH = IMAGE_INFO_LABEL_WIDTH
COMMENTS_SECTION_FRAME_HEIGHT = 200
COMMENTS_SECTION_FRAME_BACKGROUND = "#FFFFFF"
COMMENTS_SECTION_FRAME_ROW = 1  # Adjusted to match IMAGE_INFO_LABEL_ROW + 1
COMMENTS_SECTION_FRAME_COLUMN = 1  # Same as IMAGE_INFO_LABEL_COLUMN
COMMENTS_SECTION_FRAME_STICKY = "nsew"
COMMENTS_SECTION_FRAME_PADX = 2
COMMENTS_SECTION_FRAME_PADY = 2
COMMENTS_SECTION_SCROLLBAR_COLOR = "#CCCCCC"
COMMENTS_SECTION_SCROLLBAR_HOVER_COLOR = "#999999"

# Comment Frame Constants
COMMENT_FRAME_BACKGROUND = "#F0F0F0"
COMMENT_FRAME_CORNER_RADIUS = 5
COMMENT_FRAME_PADY = 5

# Comment Text Constants
COMMENT_USER_FONT = ("Arial", 12, "bold")
COMMENT_USER_TEXT_COLOR = "#333333"
COMMENT_TEXT_FONT = ("Arial", 11)
COMMENT_TEXT_COLOR = "#555555"
COMMENT_PADX = 5


# Reaction button constants
COMMENT_REACTION_BUTTON_WIDTH = 1
COMMENT_REACTION_BUTTON_HEIGHT = 1
COMMENT_REACTION_BUTTON_FONT = ("Arial", 12)
COMMENT_REACTION_BUTTON_BG = "#123456"
COMMENT_REACTION_BUTTON_HOVER_COLOR = "#C0C0C0"
COMMENT_REACTION_BUTTON_SPACING = 5

REACTIONS_FRAME_HEIGHT = 100
REACTIONS_FRAME_WIDTH = 7 
REACTION_FRAME_RELX = 0 #0.9
REACTION_FRAME_RELY = 0.5 #Changed from 0.65 to 0.58 to fit in agree/disagree stats -AG🟨  #never mind, having 1,1 moved it outside the frame boundaies #0.9 this win become 1, 1, which will always place it at the bottom right corner    
REACTION_FRAME_BACKGROUND = '#0123FF'
NUMBER_OF_BUTTONS = 8 #changed from 5 to 6   
REACTION_BUTTON_WIDTH = REACTIONS_FRAME_WIDTH
REACTION_BUTTON_HEIGHT = REACTIONS_FRAME_HEIGHT*NUMBER_OF_BUTTONS
REACTION_BUTTON_CORNER_RADIUS = 5

QUESTION_BUTTON_BACKGROUND = 'BLUE'
QUESTION_BUTTON_TEXT = '❓'

SHARE_BUTTON_FOREGROUND = 'BLACK'
SHARE_BUTTON_TEXT = '🔗'

INFO_BUTTON_BACKGROUND = 'YELLOW'
INFO_BUTTON_TEXT = 'ℹ️'

AGREE_BUTTON_BACKGROUND = 'GREEN'
DISAGREE_BUTTON_BACKGROUND = 'RED'
QUESTION_BUTTON_BACKGROUND = 'BLUE'
INFO_BUTTON_BACKGROUND = 'YELLOW'
SHARE_BUTTON_BACKGROUND = 'WHITE'


'''To be kept, and potentially added in future versions
# NEXT_PREVIOUS_BUTTON_FRAME = NONE
# NEXT_PREVIOUS_BUTTON_FRAME_ROW = 2
# NEXT_PREVIOUS_BUTTON_FRAME_COLUMN = 0
# NEXT_PREVIOUS_BUTTON_FRAME_STICKY = NSEW
# NEXT_PREVIOUS_BUTTON_FRAME_PADX = 0
# NEXT_PREVIOUS_BUTTON_FRAME_PADY = 0

# next_previous_button_frame = Frame(
#     master= tab_view.tab(TRENDS),
# )
# next_previous_button_frame.grid(
#     row = NEXT_PREVIOUS_BUTTON_FRAME_ROW,
#     column = NEXT_PREVIOUS_BUTTON_FRAME_COLUMN,
#     sticky = NEXT_PREVIOUS_BUTTON_FRAME_STICKY,
#     padx= NEXT_PREVIOUS_BUTTON_FRAME_PADY,
#     pady= NEXT_PREVIOUS_BUTTON_FRAME_PADY
# )'''

NEXT_PETITION_BUTTON = NONE
NEXT_PETITION_BUTTON_TEXT = 'Next Petition ➡️'
NEXT_PETITION_BUTTON_ROW = 2
NEXT_PETITION_BUTTON_COLUMN = 0
NEXT_PETITION_BUTTON_STICKY = NSEW
NEXT_PETITION_BUTTON_PADX = 10
NEXT_PETITION_BUTTON_PADY = 0

PREVIOUS_PETITION_BUTTON = NONE
PREVIOUS_PETITION_BUTTON_TEXT = 'Previous Petition ⬅️'
PREVIOUS_PETITION_BUTTON_ROW = 3
PREVIOUS_PETITION_BUTTON_COLUMN = 0
PREVIOUS_PETITION_BUTTON_STICKY = NSEW
PREVIOUS_PETITION_BUTTON_PADX = 10
PREVIOUS_PETITION_BUTTON_PADY = 0

'''NEW PETITION TAB CONSTANTS'''

NEW_PETITION_FRAME = NONE # JUST TO MAKE IT EASIER - INSTEAD OF TYPING IT REPEATEDLY, THE VARIABE IS NOW AUTOSUGGESTED
NEW_PETITION_BACKGROUND = '#aaadda'
NEW_PETITION_FRAME_WIDTH = WINDOW_WIDTH
NEW_PETITION_FRAME_HEIGHT = 520
NEW_PETITION_FRAME_RELX = 0.02
NEW_PETITION_FRAME_RELY = 0.04
NEW_PETITION_FRAME_RELWIDTH = 1
NEW_PETITION_FRAME_RELHEIGHT = 1
NEW_PETITION_FRAME_BORDER = 2   
NEW_PETITION_FRAME_CURSOR = 'shuttle'
NEW_PETITION_FRAME_PADX = 10
NEW_PETITION_FRAME_PADY = 5

PICTURE_PREVIEW = NONE
PICTURE_PREVIEW_BACKGROUND = 'HOME_WINDOW_ICON.jpg'
PICTURE_PREVIEW_TEXT = 'Click UPLOAD PICTURE to preview your image ➡️'
PICTURE_PREVIEW_WIDTH = 400  #check next line #75 this was also for the frame object  #400 was too big for the label
PICTURE_PREVIEW_HEIGHT = 400 #i finally ended up using 500 for the canvas #25 this was for a frame object #400 was too big for the label
PICTURE_PREVIEW_ROW = 0
PICTURE_PREVIEW_ROWSPAN = 1
PICTURE_PREVIEW_COLUMN = 0
PICTURE_PREVIEW_COLUMNSPAN = 1
PICTURE_PREVIEW_PADX = 10
PICTURE_PREVIEW_PADY = 10
PICTURE_PREVIEW_IMAGE = NONE
PICTURE_PREVIEW_IMAGE_SIZE = [400, 400]

PETITION_BUTTON_TEXT = 'Petition!'
PETITION_BUTTON_WIDTH = 120  # Width of the button in px
PETITION_BUTTON_HEIGHT = 40  # Height of the button in px
PETITION_BUTTON_CORNER_RADIUS = 10  # Corner radius in px
PETITION_BUTTON_BORDER_WIDTH = 2  # Border width in px
PETITION_BUTTON_FG_COLOR = '#2CC985'  # Foreground color (light green)
PETITION_BUTTON_HOVER_COLOR = '#1AA565'  # Hover color (darker green)
PETITION_BUTTON_BORDER_COLOR = '#2CC985'  # Border color (same as foreground)
PETITION_BUTTON_TEXT_COLOR = 'white'  # Text color
PETITION_BUTTON_FONT = ('Arial', 14)  # Font and size
PETITION_BUTTON_STATE = 'normal'  # Button state
PETITION_BUTTON_HOVER = True  # Enable hover effect
PETITION_BUTTON_ROW = 5  # Grid row
PETITION_BUTTON_COLUMN = 0  # Grid column
PETITION_BUTTON_STICKY = 'NSEW'  # Grid sticky

POST_DESCRIPTION_FRAME = NONE
POST_DESCRIPTION_FRAME_ROW = 0
POST_DESCRIPTION_FRAME_ROWSPAN = PICTURE_PREVIEW_ROWSPAN
POST_DESCRIPTION_FRAME_COLUMN = 2
POST_DESCRIPTION_FRAME_COLUMNSPAN = 1
POST_DESCRIPTION_FRAME_PADX = 10
POST_DESCRIPTION_FRAME_PADY = 10
POST_DESCRIPTION_FRAME_STICKY = NSEW
POST_DESCRIPTION_FRAME_BACKGROUND = 'NAVY'
POST_DESCRIPTION_FRAME_WIDTH = 400
POST_DESCRIPTION_FRAME_HEIGHT = 10

LOCATION_DROPDOWN = NONE
LOCATION_DROPDOWN_TEXT = 'SElECT LOCATIONS'
LOCATION_DROPDOWN_VALUES = ['Tajmahal Road', 'Block C', 'Mohammadpur', 'Dhaka', 'Dhaka Division', 'Bangladesh', 'South Asia', 'Asia', 'Earth']
LOCATION_DROPDOWN_ROW = PETITION_BUTTON_ROW+1
LOCATION_DROPDOWN_COLUMN = 0
LOCATION_DROPDOWN_STICKY = NSEW

POST_TITLE_LABEL_TEXT = 'ENTER PETITION TITLE'
POST_TITLE_ENTRY = NONE
POST_TITLE_ENTRY_PLACEHOLDER = 'ENTER PETITION TITLE'
POST_TITLE_ENTRY_RELIEF = 'raised'
POST_TITLE_ENTRY_BORDERWIDTH = 5
POST_TITLE_ENTRY_WIDTH = 30
POST_TITLE_ENTRY_ROW = 1
POST_TITLE_ENTRY_COLUMN = 0
POST_TITLE_ENTRY_STICKY = NSEW
POST_TITLE_ENTRY_PADX = 2
POST_TITLE_ENTRY_PADY = 0

DESCRIPTION_LABEL = NONE
DESCRIPTION_LABEL_TEXT = 'ENTER PETITION DESCRIPTION'
DESCRIPTION_LABEL_FONT = ('Arial', 14)
DESCRIPTION_LABEL_FOREGROUND = 'WHITE'
DESCRIPTION_LABEL_BACKGROUND = 'NAVY'
DESCRIPTION_LABEL_BORDERWIDTH = POST_TITLE_ENTRY_BORDERWIDTH
DESCRIPTION_LABEL_WIDTH = POST_TITLE_ENTRY_WIDTH
DESCRIPTION_LABEL_ROW = 2
DESCRIPTION_LABEL_COLUMN = 0
DESCRIPTION_LABEL_STICKY = NSEW
DESCRIPTION_LABEL_PADX = 0
DESCRIPTION_LABEL_PADY = 0


DESCRIPTION_TEXTBOX = NONE
DESCRIPTION_TEXTBOX_TEXT = 'ENTER PETITION DESCRIPTION'
DESCRIPTION_TEXTBOX_TEXT_COLOUR = 'BLACK'
DESCRIPTION_TEXTBOX_BACKGROUND = '#ADADAD'
DESCRIPTION_TEXTBOX_FG_COLOUR = 'transparent' #	main widget color, tuple: (light_color, dark_color) or single color or "transparent"
DESCRIPTION_TEXTBOX_BORDER_COLOUR = 'BLACK'
DESCRIPTION_TEXTBOX_BORDER_WIDTH = 5
DESCRIPTION_TEXTBOX_WIDTH = 400
DESCRIPTION_TEXTBOX_WRAP = 'word'
DESCRIPTION_TEXTBOX_CORNER_RADIUS = 10
DESCRIPTION_TEXTBOX_ROW = 3
DESCRIPTION_TEXTBOX_COLUMN = 0
DESCRIPTION_TEXTBOX_STICKY = 'NSEW'

# UPLOAD_CANCEL_BUTTON_FRAME_WIDTH = 
UPLOAD_CANCEL_BUTTON_FRAME_ROW = LOCATION_DROPDOWN_ROW + 1
UPLOAD_CANCEL_BUTTON_FRAME_COLUMN = 0
UPLOAD_CANCEL_BUTTON_FRAME_COLUMNSPAN = PICTURE_PREVIEW_COLUMNSPAN + 2
UPLOAD_CANCEL_BUTTON_FRAME_STICKY = NS

UPLOAD_BUTTON = NONE
UPLOAD_BUTTON_TEXT = 'UPLOAD PICTURE'
UPLOAD_BUTTON_WIDHT = 30
UPLOAD_BUTTON_HEIGHT = 1
UPLOAD_BUTTON_BACKGROUND = 'BLUE'
UPLOAD_BUTTON_FOREGROUND = '#aaaaaa'
UPLOAD_BUTTON_COMMAND = NONE
UPLOAD_BUTTON_RELX = 0.9 # currently not being used
UPLOAD_BUTTON_RELY = 0 # currently not being used too
UPLOAD_BUTTON_ROW = 0
UPLOAD_BUTTON_COLUMN = 0
UPLOAD_BUTTON_STICKY = EW

CANCEL_UPLOAD_BUTTON_TEXT = 'CANCEL UPLOAD'
CANCEL_UPLOAD_BUTTON_WIDTH = 30  # Width of the button in characters
CANCEL_UPLOAD_BUTTON_HEIGHT = 1  # Height of the button in lines
CANCEL_UPLOAD_BUTTON_BACKGROUND = 'red'  # Background color
CANCEL_UPLOAD_BUTTON_FOREGROUND = 'white'  # Text color
CANCEL_UPLOAD_BUTTON_RELX = 0.9 # currently not being used
CANCEL_UPLOAD_BUTTON_RELY = 0.05 # currently not being used too
CANCEL_UPLOAD_BUTTON_ROW = 0
CANCEL_UPLOAD_BUTTON_COLUMN = 1
CANCEL_UPLOAD_BUTTON_STICKY = EW

URGENT_CHECKBOX_TEXT = 'URGENT'
URGENT_CHECKBOX_TEXT_COLOR = 'WHITE'  # Text color
URGENT_CHECKBOX_BACKGROUND = POST_DESCRIPTION_FRAME_BACKGROUND  # Background color
URGENT_CHECKBOX_FG_COLOR = 'PURPLE'  # Foreground (main widget) color
URGENT_CHECKBOX_BORDER_COLOR = 'black'  # Border color
URGENT_CHECKBOX_BORDER_WIDTH = 1  # Border width in px
URGENT_CHECKBOX_WIDTH = 100  # Width of the widget in px
URGENT_CHECKBOX_HEIGHT = 20  # Height of the widget in px
URGENT_CHECKBOX_CORNER_RADIUS = 5  # Corner radius in px
URGENT_CHECKBOX_HOVER_COLOR = 'gray'  # Hover color
URGENT_CHECKBOX_ROW = 4  # Grid row
URGENT_CHECKBOX_COLUMN = 0  # Grid column
URGENT_CHECKBOX_STICKY = 'NSEW'  # Grid sticky



# Comment petitioning section constants
COMMENT_ENTRY_FRAME_WIDTH = IMAGE_INFO_LABEL_WIDTH
COMMENT_ENTRY_FRAME_HEIGHT = 100
COMMENT_ENTRY_FRAME_BACKGROUND = "#FFFFFF"
COMMENT_ENTRY_FRAME_ROW = 2  # Below comments section
COMMENT_ENTRY_FRAME_COLUMN = 1
COMMENT_ENTRY_FRAME_STICKY = "nsew"
COMMENT_ENTRY_FRAME_PADX = 2
COMMENT_ENTRY_FRAME_PADY = 2

COMMENT_TEXTBOX_HEIGHT = 3
COMMENT_TEXTBOX_WIDTH = 30
COMMENT_TEXTBOX_FONT = ("Arial", 10)
COMMENT_TEXTBOX_PADX = 5
COMMENT_TEXTBOX_PADY = 5
COMMENT_TEXTBOX_WRAP = "word"

POST_COMMENT_BUTTON_TEXT = "Post Comment"
POST_COMMENT_BUTTON_WIDTH = 15
POST_COMMENT_BUTTON_HEIGHT = 1
POST_COMMENT_BUTTON_BG = "#123456"
POST_COMMENT_BUTTON_FG = "white"
POST_COMMENT_BUTTON_FONT = ("Arial", 10)
POST_COMMENT_BUTTON_PADX = 5
POST_COMMENT_BUTTON_PADY = 5